load("@rules_go//go:def.bzl", "go_library")
load("//:test_rules.bzl", "itest_go_test")

itest_go_test(
    name = "svcctl_test",
    srcs = ["svcctl_test.go"],
    services = [
        "//:services",
    ],
)

go_library(
    name = "svcctl",
    srcs = ["client.go"],
    importpath = "github.com/hermeticbuild/rules_itest/tests/svcctl",
    visibility = ["//visibility:public"],
)
