load("@aspect_rules_js//js:defs.bzl", "js_binary")
load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")
load("@rules_itest//:itest.bzl", "itest_service")
load("//:must_fail.bzl", "must_fail")
load("//:test_rules.bzl", "itest_sh_test")

bool_flag(
    name = "enforce_graceful_shutdown",
    build_setting_default = True,
    visibility = ["//visibility:public"],
)

js_binary(
    name = "server",
    entry_point = "main.mjs",
    tags = ["manual"],
)

itest_service(
    name = "service_timeout_error",
    args = ["$${PORT}"],
    autoassign_port = True,
    enforce_graceful_shutdown = ":enforce_graceful_shutdown",
    env = {
        "SHUTDOWN_WAIT_SECONDS": "1000",
    },
    exe = ":server",
    http_health_check_address = "http://localhost:$${PORT}",
    tags = ["manual"],
)

itest_service(
    name = "service_timeout_no_error",
    args = ["$${PORT}"],
    autoassign_port = True,
    env = {
        "SHUTDOWN_WAIT_SECONDS": "1000",
    },
    exe = ":server",
    http_health_check_address = "http://localhost:$${PORT}",
    tags = ["manual"],
)

itest_service(
    name = "service_graceful",
    args = ["$${PORT}"],
    autoassign_port = True,
    enforce_graceful_shutdown = ":enforce_graceful_shutdown",
    env = {
        "SHUTDOWN_WAIT_SECONDS": "1",
    },
    exe = ":server",
    http_health_check_address = "http://localhost:$${PORT}",
    shutdown_timeout = "10s",
    tags = ["manual"],
)

itest_sh_test(
    name = "graceful_shutdown_test",
    srcs = ["//:empty.sh"],
    services = [":service_graceful"],
)

itest_sh_test(
    name = "timeout_shutdown_test",
    srcs = ["//:empty.sh"],
    services = [":service_timeout_error"],
    tags = ["manual"],
)

itest_sh_test(
    name = "timeout_shutdown_no_error_test",
    srcs = ["//:empty.sh"],
    services = [":service_timeout_no_error"],
    tags = ["manual"],
)

must_fail(
    name = "shutdown_test_failure",
    test = "timeout_shutdown_test",
)
