load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_itest//:itest.bzl", "itest_task")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")
load("//:test_rules.bzl", "itest_go_test")

env = {
    "ITEST_ENV_VAR": "ITEST_ENV_VAR_VALUE",
    "ENV_RUNFILE": "$(rlocationpath :test.txt)",
}

itest_go_test(
    name = "env_test",
    srcs = ["env_test.go"],
    data = [":test.txt"],
    env = env,
    deps = ["@rules_go//go/runfiles"],
)

cc_binary(
    name = "_task_cc",
    srcs = ["task.cc"],
    data = [
        ":test.txt",
    ],
    env = env,
)

itest_task(
    name = "task_cc",
    exe = ":_task_cc",
)

sh_binary(
    name = "_task_sh",
    srcs = ["task.sh"],
    data = [
        ":test.txt",
    ],
    env = env,
)

itest_task(
    name = "task_sh",
    exe = ":_task_sh",
    # sh_binary does not provide RunEnvironmentInfo.
    tags = ["manual"],
)
