load("@rules_itest//:itest.bzl", "itest_task")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")
load("//:test_rules.bzl", "itest_sh_test")

sh_binary(
    name = "write_to_file",
    srcs = ["write.sh"],
)

MESSAGE = "hello world"

[
    itest_task(
        name = "write_" + str(i),
        args = [
            MESSAGE[i],
        ],
        exe = ":write_to_file",
        deps = [":write_" + str(i - 1)] if i > 0 else [],
    )
    for i in range(len(MESSAGE))
]

itest_sh_test(
    name = "dependencies_test",
    srcs = ["test.sh"],
    services = [":write_10"],
)
